export type Language = "en" | "es";

const copy = {
  operations: ["Operations", "Operaciones"], incidents: ["Incidents", "Incidentes"], intelligence: ["Intelligence", "Inteligencia"], approvals: ["Approvals", "Aprobaciones"], audit: ["Audit log", "Registro de auditoría"], access: ["Access control", "Control de acceso"],
  command: ["IRIS COMMAND CENTER", "CENTRO DE CONTROL IRIS"], securityOperations: ["Security operations", "Operaciones de seguridad"], incidentResponse: ["Incident response", "Respuesta a incidentes"], threatIntelligence: ["Threat intelligence", "Inteligencia de amenazas"], approvalCenter: ["Approval center", "Centro de aprobaciones"],
  connected: ["Live systems", "Sistemas en vivo"], updated: ["Updated", "Actualizado"], now: ["just now", "ahora mismo"], signOut: ["Sign out", "Cerrar sesión"],
  riskScore: ["Risk score", "Puntuación de riesgo"], elevated: ["Elevated", "Elevado"], openIncidents: ["Open incidents", "Incidentes abiertos"], critical: ["critical", "críticos"], protectedAssets: ["Protected assets", "Activos protegidos"], healthy: ["healthy", "saludables"], meanResponse: ["Mean response", "Respuesta promedio"], today: ["today", "hoy"],
  liveActivity: ["Live security activity", "Actividad de seguridad"], rankedSignals: ["Signals from your Mac agent, wallet, and purchases", "Señales de tu agente Mac, la wallet y las compras"], evidence: ["Correlated evidence", "Evidencia correlacionada"], recommended: ["Recommended response", "Respuesta recomendada"], reviewPlan: ["Review response plan", "Revisar plan de respuesta"], contained: ["Contained", "Contenido"],
  allIncidents: ["All incidents", "Todos los incidentes"], selectIncident: ["Select an incident to view its analysis, evidence, and approve its correction.", "Selecciona un incidente para ver el análisis, la evidencia y aprobar su corrección."], whatHappened: ["What happened?", "¿Qué ocurrió?"], probableCause: ["Probable cause", "Causa probable"], impact: ["Impact", "Impacto"], confidence: ["IRIS confidence", "Confianza de IRIS"], proposedPlan: ["Plan proposed by IRIS", "Plan que IRIS propone ejecutar"], demoMode: ["Live response", "Respuesta en vivo"], demoWarning: ["Approving notifies your Mac agent and, for the firewall, can enable it after macOS asks for your password. IRIS does not change other settings silently.", "Al aprobar, IRIS avisa a tu agente Mac y, si es el firewall, puede activarlo después de que macOS pida tu contraseña. IRIS no cambia otros ajustes en silencio."], requestApproval: ["Request my approval", "Solicitar mi aprobación"], incidentContained: ["Incident contained", "Incidente contenido"],
  approvalRequired: ["APPROVAL REQUIRED", "APROBACIÓN REQUERIDA"], authorize: ["Authorize response for", "Autorizar respuesta para"], secureConfirmation: ["Secure confirmation", "Confirmación segura"], simulationOnly: ["This is a live action. IRIS will notify the Mac agent and wait for the next verified report. Purchases only open the official checkout.", "Esta es una acción en vivo. IRIS avisará al agente del Mac y esperará el siguiente reporte verificado. Las compras solo abren el checkout oficial."], cancel: ["Cancel", "Cancelar"], approveSimulation: ["Approve and run live", "Aprobar y ejecutar en vivo"],
  pendingApprovals: ["Pending approvals", "Aprobaciones pendientes"], approvalExplain: ["IRIS waits for your authorization before every response action.", "IRIS espera tu autorización antes de cada acción de respuesta."], noPending: ["No actions require approval.", "No hay acciones que requieran aprobación."], review: ["Review", "Revisar"],
  malicious: ["Malicious indicators", "Indicadores maliciosos"], campaigns: ["Active campaigns", "Campañas activas"], blocked: ["Blocked connections", "Conexiones bloqueadas"], hours: ["in 24 hours", "en 24 horas"], sector: ["target your sector", "dirigidas a tu sector"], pastWeek: ["Past 7 days", "Últimos 7 días"], trend: ["Threat activity trend", "Tendencia de amenazas"], techniques: ["Top observed techniques", "Técnicas principales"], latestIndicators: ["Latest indicators", "Indicadores recientes"], liveFeed: ["LIVE FEED", "FUENTE ACTIVA"],
  immutableAudit: ["Immutable audit trail", "Registro de auditoría inmutable"], auditExplain: ["Authentication, investigation, and response actions recorded by IRIS.", "Acciones de autenticación, investigación y respuesta registradas por IRIS."], records: ["records", "registros"], time: ["Time", "Hora"], actor: ["Actor", "Actor"], action: ["Action", "Acción"], resource: ["Resource", "Recurso"], outcome: ["Outcome", "Resultado"],
  filterAll: ["All", "Todos"], filterCritical: ["Critical", "Crítico"], filterHigh: ["High", "Alto"], filterMedium: ["Medium", "Medio"], statusOpen: ["OPEN", "ABIERTO"], statusInvestigating: ["INVESTIGATING", "EN INVESTIGACIÓN"], statusContained: ["CONTAINED", "CONTENIDO"],
} as const;

export type CopyKey = keyof typeof copy;
export const text = (key: CopyKey, language: Language) => copy[key][language === "en" ? 0 : 1];

export const incidentSpanish: Record<string, { title: string; source: string; summary: string; cause: string; impact: string; evidence: string[]; actions: string[]; recommendation: string }> = {};
