export type Language = "en" | "es";

const copy = {
  operations: ["Operations", "Operaciones"], incidents: ["Incidents", "Incidentes"], intelligence: ["Intelligence", "Inteligencia"], approvals: ["Approvals", "Aprobaciones"], audit: ["Audit log", "Registro de auditoría"], access: ["Access control", "Control de acceso"],
  command: ["IRIS COMMAND CENTER", "CENTRO DE CONTROL IRIS"], securityOperations: ["Security operations", "Operaciones de seguridad"], incidentResponse: ["Incident response", "Respuesta a incidentes"], threatIntelligence: ["Threat intelligence", "Inteligencia de amenazas"], approvalCenter: ["Approval center", "Centro de aprobaciones"],
  connected: ["Demo systems connected", "Sistemas de demostración conectados"], updated: ["Updated", "Actualizado"], now: ["just now", "ahora mismo"], signOut: ["Sign out", "Cerrar sesión"],
  riskScore: ["Risk score", "Puntuación de riesgo"], elevated: ["Elevated", "Elevado"], openIncidents: ["Open incidents", "Incidentes abiertos"], critical: ["critical", "críticos"], protectedAssets: ["Protected assets", "Activos protegidos"], healthy: ["healthy", "saludables"], meanResponse: ["Mean response", "Respuesta promedio"], today: ["today", "hoy"],
  liveActivity: ["Live security activity", "Actividad de seguridad"], rankedSignals: ["Correlated demo signals ranked by operational risk", "Señales de demostración correlacionadas por riesgo operativo"], evidence: ["Correlated evidence", "Evidencia correlacionada"], recommended: ["Recommended response", "Respuesta recomendada"], reviewPlan: ["Review response plan", "Revisar plan de respuesta"], contained: ["Contained", "Contenido"],
  allIncidents: ["All incidents", "Todos los incidentes"], selectIncident: ["Select an incident to view its analysis, evidence, and approve its correction.", "Selecciona un incidente para ver el análisis, la evidencia y aprobar su corrección."], whatHappened: ["What happened?", "¿Qué ocurrió?"], probableCause: ["Probable cause", "Causa probable"], impact: ["Impact", "Impacto"], confidence: ["IRIS confidence", "Confianza de IRIS"], proposedPlan: ["Plan proposed by IRIS", "Plan que IRIS propone ejecutar"], demoMode: ["Demo mode", "Modo de prueba"], demoWarning: ["These actions are simulated. IRIS is not connected to your computer, firewall, or user directory.", "Estas acciones se simulan. IRIS no tiene conexión con tu computadora, firewall o directorio de usuarios."], requestApproval: ["Request my approval", "Solicitar mi aprobación"], incidentContained: ["Incident contained", "Incidente contenido"],
  approvalRequired: ["APPROVAL REQUIRED", "APROBACIÓN REQUERIDA"], authorize: ["Authorize response for", "Autorizar respuesta para"], secureConfirmation: ["Secure confirmation", "Confirmación segura"], simulationOnly: ["At this testing stage, only the status inside IRIS will change. No real systems will be modified.", "En esta etapa de prueba solo se actualizará el estado dentro de IRIS. No se ejecutarán cambios en sistemas reales."], cancel: ["Cancel", "Cancelar"], approveSimulation: ["Approve and run simulation", "Aprobar y ejecutar simulación"],
  pendingApprovals: ["Pending approvals", "Aprobaciones pendientes"], approvalExplain: ["IRIS waits for your authorization before every response action.", "IRIS espera tu autorización antes de cada acción de respuesta."], noPending: ["No actions require approval.", "No hay acciones que requieran aprobación."], review: ["Review", "Revisar"],
  malicious: ["Malicious indicators", "Indicadores maliciosos"], campaigns: ["Active campaigns", "Campañas activas"], blocked: ["Blocked connections", "Conexiones bloqueadas"], hours: ["in 24 hours", "en 24 horas"], sector: ["target your sector", "dirigidas a tu sector"], pastWeek: ["Past 7 days", "Últimos 7 días"], trend: ["Threat activity trend", "Tendencia de amenazas"], techniques: ["Top observed techniques", "Técnicas principales"], latestIndicators: ["Latest indicators", "Indicadores recientes"], liveFeed: ["LIVE FEED", "FUENTE ACTIVA"],
  immutableAudit: ["Immutable audit trail", "Registro de auditoría inmutable"], auditExplain: ["Authentication, investigation, and response actions recorded by IRIS.", "Acciones de autenticación, investigación y respuesta registradas por IRIS."], records: ["records", "registros"], time: ["Time", "Hora"], actor: ["Actor", "Actor"], action: ["Action", "Acción"], resource: ["Resource", "Recurso"], outcome: ["Outcome", "Resultado"],
  filterAll: ["All", "Todos"], filterCritical: ["Critical", "Crítico"], filterHigh: ["High", "Alto"], filterMedium: ["Medium", "Medio"], statusOpen: ["OPEN", "ABIERTO"], statusInvestigating: ["INVESTIGATING", "EN INVESTIGACIÓN"], statusContained: ["CONTAINED", "CONTENIDO"],
} as const;

export type CopyKey = keyof typeof copy;
export const text = (key: CopyKey, language: Language) => copy[key][language === "en" ? 0 : 1];

export const incidentSpanish: Record<string, { title: string; source: string; summary: string; cause: string; impact: string; evidence: string[]; actions: string[]; recommendation: string }> = {
  "IR-1042": { title:"Conexión saliente anómala", source:"Sensor de red", summary:"El equipo WS-1025 inició una transferencia inusual hacia un destino nunca observado. El patrón puede indicar extracción de datos o comunicación con un servidor de mando y control.", cause:"Proceso desconocido ejecutado después de un inicio de sesión privilegiado.", impact:"Posible exposición de datos y control remoto del equipo afectado.", evidence:["Destino observado por primera vez","4.8 GB transferidos en 11 minutos","La conexión ocurrió después de un acceso privilegiado"], actions:["Aislar WS-1025 de la red","Bloquear 203.0.113.45","Conservar memoria y registros","Abrir investigación forense"], recommendation:"Aislar el equipo, bloquear el destino y preservar la evidencia antes de cerrar conexiones o procesos." },
  "IR-1041": { title:"Inicio de sesión sospechoso bloqueado", source:"Identidad", summary:"Se bloqueó un intento de acceso incompatible con la ubicación habitual del usuario y con múltiples fallos de autenticación.", cause:"Credenciales posiblemente comprometidas o intento automatizado de acceso.", impact:"La sesión fue bloqueada; no hay evidencia de acceso exitoso.", evidence:["Desplazamiento imposible detectado","Dos desafíos MFA fallidos","IP de origen con mala reputación"], actions:["Revocar sesiones activas","Solicitar cambio de contraseña","Verificar al usuario por un canal aprobado"], recommendation:"Restablecer las sesiones y verificar la identidad del usuario antes de reactivar el acceso." },
  "IR-1039": { title:"Anomalía de actividad en base de datos", source:"Base de datos", summary:"La base de datos recibió un volumen de consultas muy superior al normal mediante una cuenta de servicio fuera de su horario habitual.", cause:"Automatización defectuosa, credencial expuesta o cambio no documentado.", impact:"Riesgo de lectura masiva de información y degradación del servicio.", evidence:["Volumen de consultas 6.2× sobre la línea base","Cuenta utilizada fuera del horario normal","No existe ticket de cambio aprobado"], actions:["Pausar temporalmente la credencial","Capturar las consultas recientes","Comparar con el registro de despliegues"], recommendation:"Pausar la credencial de servicio y validar las consultas antes de restaurarla." },
  "IR-1036": { title:"Acceso privilegiado concedido", source:"PAM", summary:"Se otorgó acceso administrativo temporal a una cuenta de servicio. La aprobación existe, pero la sesión continúa bajo observación.", cause:"Elevación programada para realizar una tarea administrativa.", impact:"Riesgo controlado mientras la sesión permanezca grabada y dentro del tiempo autorizado.", evidence:["Rol administrativo temporal otorgado","Cadena de aprobación completa","Grabación de sesión activa"], actions:["Vigilar la sesión","Confirmar el ticket de trabajo","Revocar el privilegio al vencimiento"], recommendation:"Mantener la supervisión y confirmar el cierre del ticket antes de dar por resuelto el incidente." },
  "IR-1032": { title:"Verificación de política completada", source:"Cumplimiento", summary:"La evaluación DLP finalizó sin fallos críticos. Dos controles produjeron advertencias que requieren revisión programada.", cause:"Dos configuraciones no cumplen completamente el nivel recomendado.", impact:"Sin impacto activo; existe una brecha menor de cumplimiento.", evidence:["148 controles evaluados","2 advertencias registradas","Ningún fallo crítico"], actions:["Revisar los dos controles","Asignar responsable","Validar nuevamente en el próximo ciclo"], recommendation:"Revisar las advertencias durante el siguiente ciclo de políticas." },
};
